### ISSUE TITLE
How to make it run as a stand-alone application after it is released?

### ISSUE THREAD

**Issue by 199621616** [taherfattahi/BlazorWinformsWebView2#1]

**Comment by taherfattahi** [comment]
I found a tricky solution, you can **publish** Blazor.Server project with `dotnet publish` command or right click on Blazor.Server and click on `Publish..` and then you have a `Blazor.Server.exe` file. then use this code before `new WebView2()`: 
```
using System.Diagnostics;
////

  Process.Start("C:\\Blazor.Server.exe");
  WebView2 webView2 = new WebView2();
  webView2.Source = new Uri("https://localhost:5001/");
  webView2.Dock = DockStyle.Fill;
  this.Controls.Add(webView2);
```
but if I could reach a better solution, i will tell you

**Comment by 199621616** [comment]
If blazorserver is available Microsoft.Data.Sqlite Access to local database, remote access to webapi using httpclient, I feel that it is very suitable for me

**Comment by taherfattahi** [comment]
yes, this is a good solution.
you can use **socket TCP/UDP** between blazor server side and your webapi project.
blazor server side support **TCP socket** but you cant use **TCP socket** in blazor client side. 
https://jspuij.github.io/BlazorWebView.Docs/pages/index.html with this library you can use TCP socket on your blazor project.

**Comment by taherfattahi** [comment]
@199621616  plz see this repository = https://github.com/taherfattahi/BlazorWinformsStandAloneApplication
